# Generated by Django 4.2 on 2024-08-12 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.BigIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=196, null=True)),
                ('enabled', models.BooleanField(blank=True, default=False, null=True)),
                ('licensed', models.BooleanField(blank=True, default=False, null=True)),
                ('expired', models.BooleanField(blank=True, default=False, null=True)),
                ('sleep_boot', models.SmallIntegerField(blank=True, default=60, null=True)),
                ('sleep_readings', models.SmallIntegerField(blank=True, default=60, null=True)),
                ('start_readings', models.BooleanField(blank=True, default=False, null=True)),
                ('dns_main', models.CharField(blank=True, max_length=230, null=True)),
                ('dns_main_token', models.CharField(blank=True, max_length=230, null=True)),
                ('dns_main_token_type', models.CharField(blank=True, max_length=60, null=True)),
                ('sleep_upload', models.SmallIntegerField(blank=True, default=20, null=True)),
                ('start_upload', models.BooleanField(blank=True, default=False, null=True)),
                ('dns_upload', models.CharField(blank=True, max_length=230, null=True)),
                ('dns_upload_token', models.CharField(blank=True, max_length=230, null=True)),
                ('dns_upload_token_type', models.CharField(blank=True, max_length=60, null=True)),
                ('sleep_feedback', models.SmallIntegerField(blank=True, default=600, null=True)),
                ('start_feedback', models.BooleanField(blank=True, default=False, null=True)),
                ('dns_feedback', models.CharField(blank=True, max_length=230, null=True)),
                ('dns_feedback_token', models.CharField(blank=True, max_length=230, null=True)),
                ('dns_feedback_token_type', models.CharField(blank=True, max_length=60, null=True)),
                ('license_check_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NetworkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('subnet_mask', models.CharField(max_length=15)),
                ('gateway', models.CharField(max_length=15)),
                ('dns', models.CharField(max_length=15)),
                ('dhcp_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_server_control', models.BooleanField(blank=True, default=False, null=True)),
                ('start_send_backup', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='new', max_length=196, null=True)),
                ('code', models.BigIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(default='modbus', max_length=30)),
                ('settings', models.JSONField(blank=True, default=dict, null=True)),
                ('last_reading', models.DateTimeField(blank=True, null=True)),
                ('readings', models.JSONField(blank=True, default=dict, null=True)),
                ('enabled', models.BooleanField(blank=True, default=False, null=True)),
                ('connected', models.BooleanField(blank=True, default=False, null=True)),
                ('is_configured', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_created_at', models.DateTimeField()),
                ('values', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.source')),
            ],
        ),
        migrations.CreateModel(
            name='LastReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.source')),
            ],
        ),
    ]
