# Generated by Django 4.2 on 2024-08-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='System',
        ),
    ]
