# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/FormConfigServer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormConfig(object):
    def setupUi(self, FormConfig):
        FormConfig.setObjectName("FormConfig")
        FormConfig.resize(589, 375)
        self.lbl_caption = QtWidgets.QLabel(FormConfig)
        self.lbl_caption.setGeometry(QtCore.QRect(10, 10, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_caption.setFont(font)
        self.lbl_caption.setObjectName("lbl_caption")

        self.retranslateUi(FormConfig)
        QtCore.QMetaObject.connectSlotsByName(FormConfig)

    def retranslateUi(self, FormConfig):
        _translate = QtCore.QCoreApplication.translate
        FormConfig.setWindowTitle(_translate("FormConfig", "Form"))
        self.lbl_caption.setText(_translate("FormConfig", "Configurações"))
