# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/FormConfigServer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormConfig(object):
    def setupUi(self, FormConfig):
        FormConfig.setObjectName("FormConfig")
        FormConfig.resize(589, 375)
        FormConfig.setMinimumSize(QtCore.QSize(589, 375))
        FormConfig.setMaximumSize(QtCore.QSize(589, 375))
        self.verticalLayout = QtWidgets.QVBoxLayout(FormConfig)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabsView = QtWidgets.QTabWidget(FormConfig)
        self.tabsView.setObjectName("tabsView")
        self.tab_settings = QtWidgets.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.btn_aplicar = QtWidgets.QPushButton(self.tab_settings)
        self.btn_aplicar.setGeometry(QtCore.QRect(470, 283, 80, 26))
        self.btn_aplicar.setObjectName("btn_aplicar")
        self.btn_reset = QtWidgets.QPushButton(self.tab_settings)
        self.btn_reset.setGeometry(QtCore.QRect(23, 283, 171, 26))
        self.btn_reset.setObjectName("btn_reset")
        self.widget = QtWidgets.QWidget(self.tab_settings)
        self.widget.setGeometry(QtCore.QRect(20, 20, 531, 52))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_server = QtWidgets.QLabel(self.widget)
        self.lbl_server.setObjectName("lbl_server")
        self.verticalLayout_2.addWidget(self.lbl_server)
        self.edt_server = QtWidgets.QLineEdit(self.widget)
        self.edt_server.setObjectName("edt_server")
        self.verticalLayout_2.addWidget(self.edt_server)
        self.widget1 = QtWidgets.QWidget(self.tab_settings)
        self.widget1.setGeometry(QtCore.QRect(425, 80, 127, 52))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_port = QtWidgets.QLabel(self.widget1)
        self.lbl_port.setObjectName("lbl_port")
        self.verticalLayout_3.addWidget(self.lbl_port)
        self.edt_port = QtWidgets.QLineEdit(self.widget1)
        self.edt_port.setObjectName("edt_port")
        self.verticalLayout_3.addWidget(self.edt_port)
        self.tabsView.addTab(self.tab_settings, "")
        self.tab_logs = QtWidgets.QWidget()
        self.tab_logs.setObjectName("tab_logs")
        self.tabsView.addTab(self.tab_logs, "")
        self.verticalLayout.addWidget(self.tabsView)

        self.retranslateUi(FormConfig)
        self.tabsView.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormConfig)

    def retranslateUi(self, FormConfig):
        _translate = QtCore.QCoreApplication.translate
        FormConfig.setWindowTitle(_translate("FormConfig", "Configurações"))
        self.btn_aplicar.setText(_translate("FormConfig", "Aplicar"))
        self.btn_reset.setText(_translate("FormConfig", "Resetar Configurações"))
        self.lbl_server.setText(_translate("FormConfig", "Servidor"))
        self.lbl_port.setText(_translate("FormConfig", "Porta"))
        self.tabsView.setTabText(self.tabsView.indexOf(self.tab_settings), _translate("FormConfig", "Configurações"))
        self.tabsView.setTabText(self.tabsView.indexOf(self.tab_logs), _translate("FormConfig", "Logs"))
