# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/ideilson/Shilde/workspace/icware/workspace-frontend/ui/FormLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormLogin(object):
    def setupUi(self, FormLogin):
        FormLogin.setObjectName("FormLogin")
        FormLogin.resize(576, 302)
        FormLogin.setMinimumSize(QtCore.QSize(576, 302))
        FormLogin.setMaximumSize(QtCore.QSize(576, 302))
        self.btn_login = QtWidgets.QPushButton(FormLogin)
        self.btn_login.setGeometry(QtCore.QRect(220, 230, 161, 41))
        self.btn_login.setObjectName("btn_login")
        self.layoutWidget = QtWidgets.QWidget(FormLogin)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 60, 401, 52))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_user = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_user.setObjectName("lbl_user")
        self.verticalLayout.addWidget(self.lbl_user)
        self.txt_user = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_user.setObjectName("txt_user")
        self.verticalLayout.addWidget(self.txt_user)
        self.layoutWidget1 = QtWidgets.QWidget(FormLogin)
        self.layoutWidget1.setGeometry(QtCore.QRect(110, 130, 401, 52))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_password = QtWidgets.QLabel(self.layoutWidget1)
        self.lbl_password.setObjectName("lbl_password")
        self.verticalLayout_2.addWidget(self.lbl_password)
        self.txt_password = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password.setObjectName("txt_password")
        self.verticalLayout_2.addWidget(self.txt_password)

        self.retranslateUi(FormLogin)
        QtCore.QMetaObject.connectSlotsByName(FormLogin)

    def retranslateUi(self, FormLogin):
        _translate = QtCore.QCoreApplication.translate
        FormLogin.setWindowTitle(_translate("FormLogin", "Controle de acesso"))
        self.btn_login.setText(_translate("FormLogin", "Entrar"))
        self.lbl_user.setText(_translate("FormLogin", "Login"))
        self.lbl_password.setText(_translate("FormLogin", "Senha"))
